### ISSUE TITLE
julia-release-basic garbage in place of prompt 

### ISSUE THREAD

**Issue by WestleyArgentum** [Keno/julia#55] opened 2012-12-10 20:13 UTC
Kenno, Jameson, you guys are awesome. Don't let anyone tell you otherwise.

That said, I've got a problem :)

Context:
Right now, I'm interfacing with julia by launching julia-release-basic as a separate process and talking over standard in and out. This approach has some serious long term limitations, to be sure, but at least up until now it has been a dead simple, practical approach. Also, I prefer julia-release-basic (and I generate a sysimg.ji with colors turned off) because it's easier to work with very simple output (to not worry about ascii color codes or extra output from julia-release-readline). 

The Problem:

```
Using pipes/files as STDIO is not yet supported. Proceed with caution!
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" to list help topics
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.0.0
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

"ìà;8
```

I omitted a couple of those STDIO warnings for brevity sake. I think that (because of something qt's process does to bind input and output) I'm using named pipes... and I started to think that was causing the garbage output in place of the prompt at the bottom. 

The thing I don't understand is why the julia banner comes though clean and only the prompt is garbage. I can restart the process over and over, get different gunk at the bottom each time, but the banner is always -metaphorically speaking- waving proudly. I even looked at julia-release-basic in a hex editor as a sanity check to see if "julia> " was actually getting compiled in.

Oh, and one final bit adding to my confusion, everything is alright in julia-release-readline. I still get the warnings about STDIO, but the julia prompt is as it should be...

Have you guys seen / heard of this in some other context and / or does anything stand out?

Thanks!

**Comment by vtjnash** [comment] 2012-12-10 20:52
In the long term, I want to provide better support for using pipes as STDIO, hence the current warning. Printing shouldn't be a problem and the "not supported" refers more to the fact it prints the banner, and reads stdin as if it was a keyboard (which can cause poor behavior).

The banner gets printed somewhat differently, which sometimes results in it being printed correct when the rest is not right. And the prompt is also printed somewhat differently also in julia-basic.

Is there any chance you could provide me with a tiny C program operates as a unit test that can be included in the julia source and run automatically to verify the ideal operation of pipes (acting more like file i/o than a repl)?

```
$ cat ../../../Desktop/test.jl | ./bin/julia-release-basic.exe -J lib/julia/sys.ji | cat -
iUsing pipes/files as STDIO is not yet supported. Proceed with caution!s
g pipes/files as STDIO is not yet supported. Proceed with caution!
ssing pipes/files as STDIO is not yet supported. Proceed with caution!U
ing pipes/files as STDIO is not yet supported. Proceed with caution!
Warning: Possible conflict in library symbol SystemFunction036
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" to list help topics
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.0.0-win32-4
 _/ |\__'_|_|_|\__'_|  |
|__/                   |

 ·.♦°·.♦à·.♦d·.♦0,.♦D,.♦println("sam")
sam

A¿R♥0~Y♥à¿R♥ AR♥?ºR♥oxF♥

A¿R♥0~Y♥à¿R♥ AR♥?ºR♥oxF♥println("greg")
greg

A¿R♥0~Y♥à¿R♥ AR♥?ºR♥oxF♥

A¿R♥0~Y♥à¿R♥ AR♥?ºR♥oxF♥println(1)
1

«☺o♦""ìbE♥oaE♥?#ç☺?XR♦

«☺o♦""ìbE♥oaE♥?#ç☺?XR♦print("bob")
bob
«☺o♦""ìbE♥oaE♥?#ç☺?XR♦

«☺o♦""ìbE♥oaE♥?#ç☺?XR♦exit()


$
```

**Comment by WestleyArgentum** [comment] 2012-12-11 03:35
I whipped this together (really quickly). It's far from a robust test of input and output, but it will verify that julia starts up and prompts a user properly. It could be extended to read some expected output from a file and to run some julia script to generate output.

```
#include <string>
#include <iostream>
#include <stdio.h>

int main(int argc, const char* argv[])
{
    if (argc != 2) {
        std::cout << "Error: Pass in the path to a julia executable. Nothing more, nothing less." << std::endl;
        return 1;
    }

    std::cout << "Starting julia for testing..." << std::endl;

    FILE* pipe = _popen(argv[1], "r");
    if (!pipe) {
        std::cout << "WARNING: Unable to launch julia for testing." << std::endl; 
        return 2;
    }

    char* expected_output = "Using pipes/files as STDIO is not yet supported. Proceed with caution!\n               _\n   _       _ _(_)_     |  A fresh approach to technical computing\n  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org\n   _ _   _| |_  __ _   |  Type \"help()\" to list help topics\n  | | | | | | |/ _` |  |\n  | | |_| | | | (_| |  |  Version 0.0.0\n _/ |\\__'_|_|_|\\__'_|  |  \n|__/                   |\n\njulia>";
    char* remaining = expected_output;

    // Before you ask, yes, I need to loop for every character. The "julia> " at the end will not be flushed until another
    // newline makes its way into the pipe, and we have no way of feeding julia input so that won't happen.
    int next_char = fgetc(pipe);
    while ((next_char != EOF) && *remaining) {
        if (*remaining != next_char)
            break;

        ++remaining;
        next_char = fgetc(pipe);
    }

    // I would close... but that would block. Julia will be terminated by the operating system when we exit.
    // _pclose(pipe);

    if (*remaining) {
        std::cout << "WARNING: Julia testing revealed something we did not expect" << std::endl;
        return 1;
    }

    std::cout << "Everything seems ok" << std::endl;
    return 0;
}
```

Anyway, the synopsis is that anything that's not a terminal definitely seems to get a garbage prompt when it starts julia... I see the repl-basic call to jl_printf that, I think, is printing the prompt. Could that be broken in my case?

More generally (and specifically): what exactly is different about the printing of the prompt?

**Comment by vtjnash** [comment] 2012-12-22 07:19
I'm marking this as a duplicate of #52. The issue is that jl_write is (currently) only safe to use for tty, although this will typically only show up as an issue when using jl_printf.

Here's my adaptation of your script that makes the output a bit more visible, and a bit less dependent on the contents of the header:

``` cpp
#include <string>
#include <iostream>
#include <stdio.h>

int main(int argc, const char* argv[])
{
    if (argc != 2) {
        std::cout << "Error: Pass in the path to a julia executable. Nothing more, nothing less." << std::endl;
        return 1;
    }

    std::cout << "Starting julia for testing..." << std::endl;

    FILE* pipe = _popen(argv[1], "r");
    if (!pipe) {
        std::cout << "WARNING: Unable to launch julia for testing." << std::endl; 
        return 2;
    }

    char* expected_output = "\njulia>";
    char* remaining = expected_output;

    // Before you ask, yes, I need to loop for every character. The "julia> " at the end will not be flushed until another
    // newline makes its way into the pipe, and we have no way of feeding julia input so that won't happen.
    int next_char = fgetc(pipe);
    while (next_char != EOF && next_char != '|') {
        std::cout << (char)next_char;
        next_char = fgetc(pipe);
    }
    int prev_char = 0;
    while (next_char != EOF && (next_char != '\n' || prev_char != '\n')) {
        std::cout << (char)next_char;
        prev_char = next_char;
        next_char = fgetc(pipe);
    }
    flush(std::cout);
    while ((next_char != EOF) && *remaining) {
        std::cout << (char)next_char;
        if (*remaining != next_char)
            break;

        ++remaining;
        next_char = fgetc(pipe);
    }
    std::cout << '\n';
    flush(std::cout);
    // I would close... but that would block. Julia will be terminated by the operating system when we exit.
    // _pclose(pipe);

    if (*remaining) {
        while ((next_char != EOF) && *remaining) {
            std::cout << (char)next_char;
            ++remaining;
            next_char = fgetc(pipe);
        }
        std::cout << '\n';
        flush(std::cout);
        std::cout << "WARNING: Julia testing revealed something we did not expect" << std::endl;
        return 1;
    }

    std::cout << "Everything seems ok" << std::endl;
    return 0;
}
```

**Closed as completed by vtjnash** 2012-12-22 07:19 UTC
